name: Test & Release
on:
  push:
    branches:
      - main
      - master
      - next
      - next-major
      - beta
      - alpha
      - "[0-9]+.x"
      - "[0-9]+.[0-9]+.x"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  test:
    name: Test
    permissions:
      contents: read
    uses: ./.github/workflows/test.yml
    with:
      upload_artifacts: true

  release:
    name: Release
    needs: test
    runs-on: ubuntu-latest
    permissions:
      # https://github.com/semantic-release/semantic-release/issues/2469
      contents: write # create releases
      issues: write # issue comments and labels
      pull-requests: write # ditto
      id-token: write # OIDC for JSR and npm trusted publishing/provenance.

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Use pnpm
        uses: pnpm/action-setup@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22.14
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Download coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage
          path: .

      - name: Download runtime results artifact
        uses: actions/download-artifact@v4
        with:
          name: runtime-results
          path: tests/runtimes

      - name: Upload coverage to gist
        uses: gaelgirodon/ci-badges-action@v1
        with:
          gist-id: 26d0f88b04b6883e1a6bba5b9b344fab
          token: ${{ secrets.GH_TOKEN_GISTS }}

      - name: Save runtime tests result to gist
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.GH_TOKEN_GISTS }}
          gist_id: f66f0ad9395e4019ec5209719377650b
          file_path: ./tests/runtimes/results.yaml

      - name: Build package
        run: pnpm run build

      - name: Release if relevant
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm exec semantic-release
